version: '3.9'

services:
  fosscord:
    image: fosscord
    restart: unless-stopped
    build:
      context: .
      args:
        PUID: ${PUID:-1000}
        PGID: ${PGID:-1000}
    ports: [ '3001-3003:3001-3003' ]
    env_file: [ '.env' ]
    volumes: [ './:/srv/fosscord-server/' ]
